spring :
  config:
    import:
      - classpath:/db/application-mysql.yml
      - classpath:/kafka/application-consumer.yml
      - classpath:/kafka/application-producer.yml

  docker:
    compose:
      enabled: true
      file: kafka/docker-compose.yml

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    open-in-view: false

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.orm.jpa: DEBUG



