spring:
  devtools:
    restart:
      enabled: false
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        #default_batch_fetch_size: 1000
    open-in-view: false

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.orm.jpa: DEBUG


